# Use the PHP 7.3 runtime (BETA) by replacing "php72" below with "php73"
runtime: php72

# Defaults to "serve index.php" and "serve public/index.php". Can be used to
# serve a custom PHP front controller (e.g. "serve backend/index.php") or to
# run a long-running PHP script as a worker process (e.g. "php worker.php").
#
# entrypoint: serve index.php
- url: /(.+\.php)$
  http_headers:
    Access-Control-Allow-Origin: *
    Access-Control-Allow-Methods: PUT, GET, POST, DELETE, OPTIONS
    Access-Control-Allow-Headers: X-PINGOTHER, origin, x-requested-with, content-type
    Access-Control-Max-Age: 86400
